### ISSUE TITLE
Crisis Core Final Fantasy VII Reunion

### ISSUE THREAD

**Issue by OKRD342** [tmplshdw/cloud_config_workaround#14]
Great project btw. Extremely helpful.

The config and saves are apparently saved in two different locations so maybe this can work with it.

config: [%LOCALAPPDATA%]\CCFF7R\Saved\Config\WindowsNoEditor\

saves: [%USERPROFILE%]\Documents\My Games\CRISIS CORE FINAL FANTASY VII REUNION\Steam\<user-id>\

**Comment by tmplshdw** [comment]
Can you tell me the filename for the config? I can add it then have you test it.

Though looking at https://steamdb.info/app/1608070/ufs/ it doesn't look like it syncs the config file only saves (*.sav) in [%USERPROFILE%]\Documents\My Games\CRISIS CORE FINAL FANTASY VII REUNION\Steam<user-id>\
so maybe this is unnecessary?
