### ISSUE TITLE
NieR: Automata (524220)

### ISSUE THREAD

**Issue by gdiazbanuelos** [tmplshdw/cloud_config_workaround#18]
Hello! Would it be possible to add Nier Automata?

Save files and config files are located under:

`%USERPROFILE%\Documents\My Games\NieR_Automata\`

This wiki shows the save and config file locations for most games:
[Nier Automata pcgamingwiki](https://www.pcgamingwiki.com/wiki/NieR:_Automata) 

Let me know if you need any more info.

**Comment by tmplshdw** [comment]
@gdiazbanuelos I was able to add this and tested it on my Deck and Linux PC. Could you try it and let me know if it works for you? The change is in this branch https://github.com/tmplshdw/cloud_config_workaround/tree/nierautomata

**Comment by gdiazbanuelos** [comment]
Thank you so much!
