### ISSUE TITLE
Horizon Zero Dawn (1151640)

### ISSUE THREAD

**Issue by tmplshdw** [tmplshdw/cloud_config_workaround#2]

**Comment by unnes** [comment]
Graphics config file for HZD on Windows appears to be at
`%UserProfile%\Documents\Horizon Zero Dawn\Saved Game\profile\graphicsconfig.ini`


Graphics config file for HZD on Steam Deck path appears to be at: 

`"/home/deck/.local/share/Steam/steamapps/compatdata/1151640/pfx/drive_c/users/steamuser/Documents/Horizon Zero Dawn/Saved Game/profile/graphicsconfig.ini"`

**Comment by unnes** [comment]
> Thanks for the info, I just added it. I can't test it directly since I don't own the game so let me know if works or not.

I just tested on my desktop Windows PC and my Steam Deck, saving a game on each and cloud loading on the other, and confirmed that it works as expected, with graphics settings remaining intact on each device. In config_workaround.log on deck, the following line shows up, but I think it's irrelevant: 

`ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.`

Thanks for updating this script so quickly, I'll be sure to use it for HZD going forward.
