### ISSUE TITLE
DRAGON QUEST XI S: Echoes of an Elusive Age – Definitive Edition (1295510)

### ISSUE THREAD

**Issue by gdiazbanuelos** [tmplshdw/cloud_config_workaround#21]
Hello again! This game stores the system settings under:
`My Games/DRAGON QUEST XI S/Steam/{Steam3AccountID}/Saved/SaveGames/Book/system999.sav`
and a backup:
`My Games/DRAGON QUEST XI S/Steam/{Steam3AccountID}/Saved/SaveGames/Book/system999.bak`

https://steamdb.info/app/1295510/ufs/

I took the script and added the if statements in the bat file and the case switch in the sh file and tested across my Windows machine and Steam Deck and it worked. I hard coded in my {Steam3AccountID} in the file path. Is there a way to implement automatically fetching the {Steam3AccountID} and place in the file path without hard coding that in?

Thank you again and let me know if you have any questions.

**Comment by tmplshdw** [comment]
Steam3AccountID is an environment variable provided by Steam so you can use it instead of hard coding. Try it with that and see if you can get it working.

**Comment by gdiazbanuelos** [comment]
How would I be able to read the Steam environment variables? I tried looking it up and I don't see much documentation on it. Thank you for the help! If I get this working I can then set up a pull request.

**Comment by gdiazbanuelos** [comment]
I have found out how to read the Steam environment variables, The only user ID I can find is STEAMID. It's specifically the steamID64 value but I need steamID3, I see there are ways of converting a steamID64 to steamID3 (I used this site https://steamid.io/lookup to convert mine and it matched the file path of {Steam3AccountID}). I will look into how to easily convert that ID but if you have any easier suggestions let me know.

**Comment by tmplshdw** [comment]
Perhaps I was mistaken with the user ID being an env variable. It might just be something available in the Steam API for the game devs. I'll look into this some more and try to find a good solution. Let me know if you discover something.

**Comment by gdiazbanuelos** [comment]
I did some digging and found out how to convert the SteamID64 to the needed SteamID3. You just subtract a constant offset of 76561197960265728 from your SteamID64 (https://gist.github.com/bcahue/4eae86ae1d10364bb66d). I tested the Python script and it worked to generate my {Steam3AccountID}. The only problem is that batch files are 32 bit only so you can't do the arithmetic. I wrote a test bat file that would externally invoke Powershell and take its output:

```
@echo off

set steamID64="YOUR STEAMD64" 
set offset="76561197960265728"

for /f "delims=" %%a in ('powershell.exe -command "$result=%steamID64%-%offset%; Write-Output $result"') do set steamID3=%%a

echo %steamID3%
```
This works when I run that bat file individually and hardcoded my SteamID. When I run it within your cloud script it doesn't output anything and when I comment out @echo off, I get some errors saying it's syntax error, or that the integer is too big for 32 bit. Even though the script runs perfectly on its own. Here is the script above injecting into the cloud code:

```
if %SteamAppId%==1295510 (
            set steamID64=%STEAMID%
            set offset="76561197960265728"
            for /f "delims=" %%a in ('powershell.exe -command "$result=%steamID64%-%offset%; Write-Output $result"') do set steamID3=%%a
            echo "GAMECONFIGDIR=%DOCUMENTS%\My Games\DRAGON QUEST XI S\Steam\%steamID3%\Saved\SaveGames\Book"
            set "GAMECONFIGDIR=%DOCUMENTS%\My Games\DRAGON QUEST XI S\Steam\%steamID3%\Saved\SaveGames\Book"
            set "GAMECONFIG=system999.sav"
)
```

**Comment by tmplshdw** [comment]
I found [this](https://gamedev.stackexchange.com/a/167219) that might be useful to solve this issue at least for the Windows side of things.

As for the stuff you found I think %STEAMID% will be empty as I don't think it's an env variable. At least I couldn't see any env variables like it when I was testing stuff earlier although I'm on Linux. Probably the syntax error is from using an empty var in the arithmetic. At least we know how to convert from one type to the other now.

Your point about the limitations of batch files make me wonder if it would be worth it to rewrite this in Powershell but I don't know enough about Windows to understand all the implications from that.

I really feel like this should have simple solution and I'm bothered that doesn't seem to be the case. Maybe we should just have a variable defined that the user can fill in with their ID and call it a day?
Something like
```
:: fill in with your SteamID
set "steamID3=12345678"
```

**Comment by gdiazbanuelos** [comment]
If I run 
```
set steamID64=%STEAMID%
echo %STEAMID%
```
It does print out my SteamID in the run time. But it does seem like a headache to get the conversion. It would probably just be easier to have the user input their ID in the script.

**Comment by tmplshdw** [comment]
I just tested in a Win 10 VM and like you say STEAMID does exist. I wonder why it doesn't seem to exist on Linux.

If we're going to do the conversion with %STEAMID% - 76561197960265728 then we'll need to give up on batch because like you said 32 bit only.

I think I'll try writing a Powershell version and see how it goes.

**Comment by tmplshdw** [comment]
@gdiazbanuelos I have a draft pull request that correctly converts the 64 bit STEAMID to the steamID3 version based on your code snippet above. I tested it in a Win10 VM but running a different game since I don't own this one. Can you take a look?

I also still need to figure out what to do on the Linux side of things but this seems like progress.

**Comment by gdiazbanuelos** [comment]
Just tested the DQ11 branch and it works on my Windows machine.

**Comment by tmplshdw** [comment]
@gdiazbanuelos I figured out a way to get the Steam ID on Linux.

Can you test the game on your Steam Deck with the DQ11 branch?

**Comment by gdiazbanuelos** [comment]
Just tested it and it works! Thank you!

**Comment by tmplshdw** [comment]
No problem, thanks for all your help figuring things out and testing
