### ISSUE TITLE
Klonoa Phantasy Reverie Series (1730680)

### ISSUE THREAD

**Issue by ds22x** [tmplshdw/cloud_config_workaround#24]
Settings are stored inside System.bin, located for Windows at:
`%USERPROFILE%\AppData\Local\Bandai Namco Entertainment/KLONOAencore\Saved\SaveGames\{Steam3AccountID}` 
and for the Linux (Steam Deck) at:
`AppData/Local/Bandai Namco Entertainment/KLONOAencore/Saved/SaveGames/${SteamID3}`

**Comment by tmplshdw** [comment]
@ds22x Thanks for the file paths. Can you test the Klonoa branch?

**Comment by ds22x** [comment]
For Windows, it should be %LOCALAPPDATA% instead of %APPDATA%.
Rest is all fine.
