### ISSUE TITLE
hogwarts legacy issue

### ISSUE THREAD

**Issue by schoeeeeeeeeee** [tmplshdw/cloud_config_workaround#33]
Hi, 

I tried to set it up so that graphics settings wouldn't sync between my pc and steam deck for hogwarts legacy. On my Steam deck I downloaded the .sh script, made it executable as instructed. put it in my documents folder and copied the path to the script as instructed to the launch options in steam for Hogwarts legacy. Unforttunately, the game won't launch when the command is active. Netiher in desktop mode nor in gaming mode. i removed it and now it's functioning perfectly again. I'm not sure what's happening here and i would appreciate any assistance.

**Comment by gdiazbanuelos** [comment]
Hello! Try deleting the .sh script and re-download it, the script should already be set as executable by default. If you open up a terminal go to where you have the script, try running `ls -la` it should output something like this `-rwxr-xr-x cloud_config_workaround.sh`. 

Also just double check that the path to the script is correct or if have any other launch commands in Steam for the game?

**Comment by schoeeeeeeeeee** [comment]
Hi, thanks for your reply and sorry for only responding now. It does not seem to download as executable by default, this is the output i'm getting:

-rw-r--r--  1 deck deck 3403 Feb 10 03:45  cloud_config_workaround.sh
-rwxr-xr-x  1 deck deck 3403 Feb  6 19:48  cloud_config_workaround.sh_edited

(the one with the _edited suffix is the one where i allowed execution)

I did as you suggested, deleted the original script, redownloaded it fresh, set it as executable. (it saved in my downloads folder) and this time it worked. And I'm pretty sure now what went wrong last time, the directory in which it was previously in had one space in it, which seems to have caused this issue. I'm really sorry for the inconvenience, this seems to be a Steam issue rather than one with the script. The script is working fine now
