### ISSUE TITLE
Death Stranding - Director's Cut

### ISSUE THREAD

**Issue by eight-track** [tmplshdw/cloud_config_workaround#35]

**Comment by eight-track** [comment]
Looking at the uploaded files I think this is the one that needs to be blocked:

KojimaProductions/DeathStrandingDC/32980838/profile/game_settings.cfg

**Comment by tmplshdw** [comment]
@eight-track Can you try the DeathStrandingDC branch here? https://github.com/tmplshdw/cloud_config_workaround/tree/DeathStrandingDC

I don't own the game so can't test it myself

**Comment by PrototypeActual** [comment]
I'm trying this branch out as I have this game. There might be some subtle differences in the paths but will report back soon to see if it works better on my Steam Deck
