### ISSUE TITLE
Metaphor: ReFantazio

### ISSUE THREAD

**Issue by OiledGladiator** [tmplshdw/cloud_config_workaround#55]
Title: Metaphor: ReFantazio
AppID: 2679460

Configuration file(s) location

Windows: %APPDATA%\SEGA\METAPHOR\Steam\<user-id>\
Linux: <SteamLibrary-folder>/steamapps/compatdata/2679460/pfx/

**Comment by tmplshdw** [comment]
If you can specify the file name I can add it or better yet you can open a PR with it

**Comment by OiledGladiator** [comment]
not really savy with this so I couldn't figure out how to do the pull request.
I made it work on my Steam Deck with 

2679460;%appdata%/SEGA/METAPHOR/%STEAMID%;pcconfig.dat

**Comment by OiledGladiator** [comment]
figured out how to do the pull request.
OiledGladiator:metaphorrefantazio
