### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by tmplshdw** [tmplshdw/cloud_config_workaround#6]
reported here 
https://old.reddit.com/r/SteamDeck/comments/vpr5a8/why_must_so_many_games_keep_syncing_their_graphic/ilby9y1/

docs https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/controlled-folders?view=o365-worldwide#windows-system-folders-are-protected-by-default

**Comment by minhnhattonthat** [comment]
It is not because of protected folders, but comes from the string variable not parsed as path.

https://stackoverflow.com/a/28115851/8575792
