### ISSUE TITLE
Persona 5 Royal

### ISSUE THREAD

**Issue by MPotts93** [tmplshdw/cloud_config_workaround#9]
APPID=1687950

**Comment by tmplshdw** [comment]
If you can tell me where the settings file is I can add it though [this thread](https://steamcommunity.com/app/1687950/discussions/0/3470612993468660405/#c3470612993468898238) makes it sound like the graphics settings are in the same file as the saves. If this is true then it wouldn't work with this script unfortunately.

**Comment by saturnv5** [comment]
@MPotts93 P5R is a tricky one, as the file path includes the user's steam ID. The video settings file is stored in savedata\SYSTEM.DAT, which was simply enough for me to add to your scripts.

For reference, the full path is: %APPDATA%\SEGA\P5R\Steam\<user-id>\savedata\SYSTEM.DAT

**Comment by tmplshdw** [comment]
Thanks for the name of the file. That will allow me to add this game to the script. I won't be able to test personally as I don't have the game but Steam makes an environment variable available for the user's steamID so that won't be an issue.

**Comment by tmplshdw** [comment]
@MPotts93 I have added a branch with P5R added. Would you be able to test it? https://github.com/tmplshdw/cloud_config_workaround/tree/P5R

**Comment by tmplshdw** [comment]
@saturnv5 Would you be willing to try the branch in the linked pull request and verify if it works?

**Comment by saturnv5** [comment]
Hi @tmplshdw, I don't have P5R installed anymore, but the path I put in your script previously is different to what you have in the branch.
For the .sh file, I have: `Application Data/SEGA/P5R/Steam/<STEAM_ID>/savedata/SYSTEM`
For the .bat file, I have: `%APPDATA%\SEGA\P5R\Steam\<STEAM_ID>\savedata\SYSTEM`

Assuming you're able to grab the correct Steam user-ID for both Win and Linux scripts, then I've verified that above paths work correctly.
